name: "Docker Build and Push with Cache"

inputs:
  docker_image:
    type: string
  docker_tag:
    type: string
  docker_username:
    type: string
  docker_password:
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Download docker build context
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: ./docker-image

    - name: Prepare Docker build context
      shell: sh
      run: |
        mkdir -p target
        cp -r ./docker-image/* target/

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: docker-${{ inputs.docker_image }}-${{ inputs.docker_tag }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          docker-${{ inputs.docker_image }}-

    - name: Docker Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile 
        push: true
        tags: ${{ inputs.docker_username }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
