name: "Defect Dojo Upload Template"

inputs:
  config:
    description: "Pipeline config"
    required: true
    type: string
  DEFECTDOJO_API_TOKEN:
    description: "DefectDojo API Token"
    required: true
    type: string
  BASE_URL:
    description: "DefectDojo base URL"
    required: false
    default: "https://defectdojo.appsec-yggdrasil.com/"
    type: string
  report:
    description: "Report name or path"
    required: false
    default: "null"
    type: string


runs:
  using: "composite"
  steps:

    - name: Create engagement
      shell: bash
      id: set-id
      env:
        API_TOKEN: ${{ inputs.DEFECTDOJO_API_TOKEN }}
        BASE_URL: ${{ inputs.BASE_URL }}
        ENGAGEMENT_NAME:  ${{ fromJson(inputs.config).global.ENGAGEMENT_NAME }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        set -e
        cd github-shared-library/scripts/defectdojo || { echo "❌ defectdojo script folder not found!"; exit 1; }

        if [ ! -f create-engagement.sh ]; then
          echo "❌ create-engagement.sh not found!"
          exit 1
        fi

        chmod +x create-engagement.sh
        echo "🚀 Running create-engagement.sh..."
        if ! ENGAGEMENT_ID=$(./create-engagement.sh 2>&1); then
          echo "❌ create-engagement.sh failed"
          echo "Output:"
          echo "$ENGAGEMENT_ID"
          exit 1
        fi
        echo "✅ Engagement created with ID: $ENGAGEMENT_ID"
        echo "engagement_id=${ENGAGEMENT_ID}" >> "$GITHUB_OUTPUT"

    - name: Upload scan results
      if: ${{ steps.check_reports.outputs.exist == 'true' }}
      shell: bash
      env:
        API_TOKEN: ${{ inputs.DEFECTDOJO_API_TOKEN }}
        BASE_URL: ${{ inputs.BASE_URL }}
        ENGAGEMENT_ID:  ${{ steps.set-id.outputs.engagement_id }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        cd github-shared-library/scripts/defectdojo || { echo "❌ defectdojo script folder not found!"; exit 1; }
        if [ ! -f upload-scan.sh ]; then
          echo "upload-scan.sh not found!"
          exit 1
        fi

        chmod +x upload-scan.sh
        ./upload-scan.sh
        echo "${{ steps.set-id.outputs.engagement_id }}"

