name: Security Tool Template
 
inputs:
  command:
    type: string
  report_name:
    type: string
  scan_type:
    type: string
  all_in_one_upload:
    type: string
  config:
    type: string
  DEFECTDOJO_API_TOKEN:
    type: string
  base_url:
    type: string
  
 
runs:
  using: "composite"
  steps:
   
    - name: "Create Report Directory"
      shell: sh
      run: |
        mkdir -p "REPORTS_DIR/temp-reports"
        chmod -R a+rw "REPORTS_DIR/temp-reports"
         
    - name: "Run Script"
      shell: bash
      run: |
        echo "${{ inputs.command }}" > command.sh
        chmod +x command.sh
        echo "${{ inputs.report_name }}" >> REPORTS_DIR/temp-reports/report_names.txt
        echo "${{ inputs.scan_type }}" >> REPORTS_DIR/temp-reports/scan_types.txt

        ./command.sh

        REPORT_FILE="REPORTS_DIR/${{ inputs.report_name }}"
        DEST_DIR="REPORTS_DIR/temp-reports"

        mkdir -p "$DEST_DIR"
        pwd

        if [[ -f "$REPORT_FILE" ]]; then
            mv "$REPORT_FILE" "$DEST_DIR/"
        else
            echo "⚠️ Report file $REPORT_FILE not found, skipping move"
        fi


      continue-on-error: true


