name: "Defect Dojo Upload Action"

inputs:
  config:
    type: string
  DEFECTDOJO_API_TOKEN:
    type: string
  BASE_URL:
    type: string
    default: "https://defectdojo.appsec-yggdrasil.com/"


runs:
  using: "composite"
  steps:
    - name: Create engagement
      shell: bash
      id: set-id
      run: |
        chmod +x github-pipeline/scripts/defectdojo/create-engagement.sh
        ENGAGEMENT_ID=$(./github-pipeline/scripts/defectdojo/create-engagement.sh)
        echo "engagement_id=${ENGAGEMENT_ID}" >> "$GITHUB_OUTPUT"
        echo "$ENGAGEMENT_ID"
      env:
        API_TOKEN: ${{ inputs.DEFECTDOJO_API_TOKEN }}
        BASE_URL: ${{ inputs.BASE_URL }}
        ENGAGEMENT_NAME:  ${{ fromJson(inputs.config).global.ENGAGEMENT_NAME }}

    - name: "Upload scan results"
      shell: bash
      run: |
        chmod +x github-pipeline/scripts/defectdojo/upload-scan.sh
        ./github-pipeline/scripts/defectdojo/upload-scan.sh
        echo "${{ steps.set-id.outputs.engagement_id }}"
      env:
        API_TOKEN: ${{ inputs.DEFECTDOJO_API_TOKEN }}
        BASE_URL: ${{ inputs.BASE_URL }}
        ENGAGEMENT_ID:  ${{ steps.set-id.outputs.engagement_id }}
